name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Format Check
        run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint Code
        run: cargo clippy -- -D warnings

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_flags: ["", "--release"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate library
        run: cargo build ${{ matrix.build_flags }}
